name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-jobe:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello world !!!"
      - name: "Segunda ação"
        run: |
          echo "Você criou oo seu primeiroo workflow !!!"
          echo "Parabéns !!!"
      - name: "Scrip Python"
        run: |
          variavel = "Hello world !!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-jobe]
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão 20.13.1 do NodeJS"
        uses: actions/setup-node@v4.0.2
        with:
         node-version: '20.13.1'
      - name: "Verificação da versão do NodeJS depois de isntalar"
        run: node --version
